---
# handlers file for install_nginx

- name: start nginx
  service: 
    name: nginx
    state: started 
    enabled: yes
  become: yes

- name: restart nginx
  service: 
    name: nginx 
    state: restarted 
  become: yes
...